### ISSUE TITLE
cannot find 'csrftoken' from cookies

### ISSUE THREAD

**Issue by Derpppr** [a1phat0ny/instascrape#11]
Seems to be a problem reported prior but I seem to be having the same issue;

```
MacBook-Pro:~ user$ instascrape --debug login

    Saved Cookies

(1) + [Login New Account]

(1-1)choice> 1
Username: username
Password: password
- Logging in...
    getting cookie by username and password
    failed to find 'csrftoken' in first attempt, using endpoint '/web/__mid'
✖ cannot find 'csrftoken' from cookies

```

Please bare with however as I am new to Python!

**Comment by a1phat0ny** [comment]
Duplicated #2

**Comment by NOBHACKER120** [comment]
Hi issue in instascrape (key error csrftoken)
Traceback (most recent call last):
File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 146, in
sess = instabrute.Login(password)
File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 110, in Login
sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'


Not working also
