### ISSUE TITLE
SAVED posts

### ISSUE THREAD

**Issue by Gahamelas** [a1phat0ny/instascrape#12]
Can this tool be used to download all my SAVED posts of my Instagram account? Thanks.

**Comment by a1phat0ny** [comment]
Yes, ofc you can!
First, you will need to log in to Instagram using `instascrape login`.
Then, use `instascrape down saved` to download all your saved posts.
All your saved posts will be downloaded to `./saved` by default.

Feel free to ask me if you have any trouble using it!

**Comment by Gahamelas** [comment]
Thanks so much! Do you know if it would save my posts in folders organized the way they are on my Instagram SAVED section? Thanks.

**Comment by Gahamelas** [comment]
When running instascrape login I get "✖ cannot find 'csrftoken' from cookies".

**Comment by a1phat0ny** [comment]
Please see #2 for more details regarding the `cannot find 'csrftoken' from cookies` issue.

**Comment by Gahamelas** [comment]
Thanks so much! Do you know if it would save my posts in folders organized the way they are on my Instagram SAVED section? Thanks.

**Comment by a1phat0ny** [comment]
No, it can't because instascrape will download the posts with the modification time automatically set to the creation time of the post, and the downloaded files will have the file name set to the post ID. Your file manager will sort them by their file name and modification time.

**Comment by Yolakalemowa** [comment]
So I had a problem... Using this, instagram blocked my account after "suspicious activity" (and b/c I logged in from a site that _looks_ like instagram...

Any solutions you think?

**Comment by tnychn** [comment]
Could you provide a screenshot of the "suspicious activity" message Instagram sent you?

**Comment by Yolakalemowa** [comment]
Well I didn't save it but found a [similar one ](https://preview.redd.it/d2mufg1sa8s51.jpg?width=320&crop=smart&auto=webp&s=18e13ae308ffcf12546485c814c8ef411dc1c4ad) from google images...

Perhaps what would solve this is to download in steps... so if I have 3,000 saved items. To download 300 and then wait 10 minutes or half hour or smthn... (I'm willing to download 300 every day even...)

**Comment by Yolakalemowa** [comment]
Any ideas?

**Comment by Yolakalemowa** [comment]
I'll just open a new issue I guess
