### ISSUE TITLE
downloads failed

### ISSUE THREAD

**Issue by swamped15** [a1phat0ny/InstaScrape#4]
Its probably me but I'd appreciate if someone could take a look at the log file and see what I am doing wrong or need to fix to make this work.  Thank you

[instascrape.log](https://github.com/a1phat0ny/InstaScrape/files/3317317/instascrape.log)

**Comment by a1phat0ny** [comment]
@swamped15 Emmm... I tried this on my Windows machine. Seems this bug occurs on Windows only. I will fix this very soon. Thanks for the bug report though!

**Comment by a1phat0ny** [comment]
@swamped15 ok I've already found the cause. It's the problem of the filename format. `:` is not allowed in filenames on Windows.

**Comment by swamped15** [comment]
thanks for taking a look! much appreciated
