### ISSUE TITLE
i installed by pip on linux (centos7.5) but i could not found command instascrape

### ISSUE THREAD

**Issue by xbb2yy** [a1phat0ny/InstaScrape#6]

**Comment by a1phat0ny** [comment]
Probably **InstaScrape** is installed to `~/.local/bin`, which is currently not in the `PATH`.

Make sure you are using Python 3.5 above. Try adding the binaries path to your `PATH` environment variable.

You can try putting the following line to your `.bashrc` or `.zshrc`:
`export PATH=$PATH:~/.local/bin`

FYI, reference: https://askubuntu.com/questions/900312/pip-install-saws-command-not-found

**Comment by xbb2yy** [comment]
> Probably **InstaScrape** is installed to `~/.local/bin`, which is currently not in the `PATH`.
> 
> Make sure you are using Python 3.5 above. Try adding the binaries path to your `PATH` environment variable.
> 
> You can try putting the following line to your `.bashrc` or `.zshrc`:
> `export PATH=$PATH:~/.local/bin`
> 
> FYI, reference: https://askubuntu.com/questions/900312/pip-install-saws-command-not-found

thanks, it helps me, instascrape is in /usr/local/python3/bin, i add it to PATH, it solved my problem
